name: Test generating classes for LabMetadataExample extension

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  run-scripts:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install C++ dependencies - macos
        run: brew install hdf5 boost catch2

      - name: Configure AqNWB 
        shell: pwsh
        run: cmake "--preset=ci-macos"

      - name: Build AqNWB 
        run: cmake --build build --config Release -j 2

      - name: Install AqNWB
        run: cmake --install build --config Release --prefix prefix

      - name: Install python script dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r resources/utils/requirements.txt

      - name: Run generate_nwb_schema_headers.sh to generated headers the LabMetadataExample extension
        run: |
          mkdir test_output
          mkdir test_output/spec
          output=$(python resources/utils/generate_spec_files.py demo/labmetadata_extension_demo/spec test_output/spec 2>&1)
          echo "$output"
          if echo "$output" | grep -q "ERROR"; then
            exit 1
          fi

      - name: Run schematype_to_aqnwb.py to generate AqNWB classes for the LabMetadataExample extension
        run: |
          python resources/utils/schematype_to_aqnwb.py --generate-test-app demo/labmetadata_extension_demo/spec/ndx-labmetadata-example.namespace.yaml test_output

      - name: List generated files
        run: | 
          ls -la build
          ls -la test_output 
      
      - name: Compile test program using generated headers
        run: |
          cd test_output/test_app
          mkdir build
          cd build
          cmake ..
          make -j 2
          ./bin/schema_compilation_test
